import "./globals.scss";
import localFont from "next/font/local";
import type { Metadata } from "next";
import { QueryParams } from "next-sanity";
import { draftMode } from "next/headers";
import { unstable_setRequestLocale } from "next-intl/server";

import { LiveVisualEditing } from "../common/components/LiveVisualEditing";
import { ENGLISH_LOCALE, FRENCH_LOCALE } from "@/../navigation";

const saansTrial = localFont({
  src: "../common/assets/fonts/SaansTRIAL-Regular.ttf",
  display: "swap",
  variable: "--font-saans-trial",
});

const centuryOldStyleStd = localFont({
  src: "../common/assets/fonts/CenturyOldStyleStd-Regular.otf",
  display: "swap",
  variable: "--font-century-old-style-std",
});

export const dynamicParams = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: QueryParams;
};

export async function generateStaticParams() {
  return [{ locale: FRENCH_LOCALE }, { locale: ENGLISH_LOCALE }];
}

const RootLayout: React.FC<RootLayoutProps> = ({ children, params }) => {
  unstable_setRequestLocale(params.locale);

  return (
    <html lang={params.locale}>
      <body className={`${saansTrial.variable} ${centuryOldStyleStd.variable}`}>
        <header>
          <nav>
            <h1>NavBar</h1>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <h1>Footer</h1>
        </footer>
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  );
};

export default RootLayout;
