import "./globals.scss";

import type { Metadata } from "next";
import { draftMode } from "next/headers";
import { Inter } from "next/font/google";
import { LiveVisualEditing } from "../common/components/LiveVisualEditing";
import { QueryParams } from "next-sanity";

const inter = Inter({ subsets: ["latin"] });

export const dynamicParams = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  params: QueryParams;
};

export async function generateStaticParams() {
  return [{ lang: "fr" }, { lang: "en" }];
}

const RootLayout: React.FC<RootLayoutProps> = ({ children, params }) => {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <main>{children}</main>
        {draftMode().isEnabled && <LiveVisualEditing />}
      </body>
    </html>
  );
};

export default RootLayout;
